databases:
- name: interview_task_2
  user: dev
  password: secret
folders:
  - map: ../
    to: /vagrant/interview-task-2
sites:
- url: localhost
  root: /vagrant/interview-task-2/public_html
apt-packages:
  - php7.2-xml
ports:
  - guest: 3306
    host: 33060
hostname: interview-task-2
name: interview-task-2