old_sound_rabbit_mq:
    connections:
        default:
            host: '%rabbitmq_host%'
            user: '%rabbitmq_user%'
            password: '%rabbitmq_password%'
    producers:
        sms:
            class: App\Producer\SmsProducer
            connection: default
            exchange_options: {name: sms_exchange, type: fanout}
    multiple_consumers:
        sms:
            connection:       default
            exchange_options: {name: sms_exchange, type: fanout}
            queues:
                sms_send:
                    name: sms_send_queue
                    callback:         App\Consumer\SmsSendConsumer
                sms_store:
                    name: sms_store_queue
                    callback:         App\Consumer\SmsStoreConsumer